FROM node:20-alpine

WORKDIR /app

COPY package.json .
COPY package-lock.json .

RUN npm install --silent

COPY src ./src
COPY public ./public
COPY db ./db
COPY configs ./configs
COPY bin ./bin
COPY tsconfig.json .
COPY .env.development .
COPY .sequelizerc .

EXPOSE 3000

CMD ["npm", "run", "dev"]
