FROM node:18.20.2-buster

WORKDIR /app
ENV PATH /app/bin:$PATH

COPY package*.json .

RUN npm install --silent

COPY . .

EXPOSE 3000

RUN chmod +x /app/bin/start_server.sh
RUN chmod +x /app/bin/www

CMD ["start_server.sh", "--env", "development"]